### ISSUE TITLE
Proposal: Graph-based Job API

### ISSUE THREAD

**Issue by aronasorman** [learningequality/iceqube#20]
# Summary
Creating a graph-based Job API for Iceqube will allow us to have more parallelism and better progress bars, while also being more robust.

# Description
Iceqube's current API is a generic asynchronous function runner -- you schedule a single python function that will run asynchronously.

This feels very clunky, and the only advantage we have over simply running `concurrent.futures` is support for progress bars. Meanwhile, we only use 1 out of the default 4 dedicated worker threads, while adding the overhead of message passing and another SQLite database. Unfortunately, keeping all the parallelizable items (e.g. I/O) inside a huge opaque python function will prevent us from parallelizing further (or parse Python AST, which is brittle).

Instead, we need to tell Iceqube which jobs depend on other jobs, and by granularly specifying what kind of job it is. By doing so, Iceqube can efficiently allocate jobs to threads, or even use compiled code to run non-Python jobs, freeing up the Python interpreter to run Python-specific code. This will also allow us to implement progress bars specific to each job.

This proposal will change `Iceqube`'s API, from a simple `client.schedule(<python function>)`, to one based on different types of `Job` classes. Each job can then specify the jobs it depends on, allowing us to construct a graph of jobs. 

# Types of Jobs
The `Job` classes are:

- `DownloadJob(url: string, dest="": string, bytes=-1: int)`: Download a file, and if the location specified by `dest`, otherwise to a temporary file. If passed to other jobs, it returns the string pointing to the destination. Passing in the # of bytes to download in the `bytes` parameter will allow Iceqube to provide an accurate progress bar sooner. Not doing so will make the progress jump around (and even be unreliable depending on the file's source) as Iceqube will only discover the # of bytes to download once it actually starts it.

```python
DownloadJob("https://google.com", "internet.html")
```

- `UploadJob(url: string, ...)`: Upload a file to the given URL. Note: incomplete, need to figure out what kind of arguments are useful for the ricecooker.

- `FileTransferJob(src: string_or_job, dest: string)`: Move a file from a source to a destination. When passed into other jobs as a dependency, it returns the string to the destination.

```python
FileTransferJob("internet.html", "google.html")
# equivalent to
FileTransferJob(DownloadJob("https://google.com"), "google.html")
```

- `CommandJob(executable: string, args: list_of_strings_or_jobs)`: Execute an external command passed with the given arguments. Jobs passed in as part of args are converted to strings, and then passed sequentially as command line arguments, e.g.:

```python
CommandJob("ls", args=["-l", DownloadJob("https://google.com"), "-a"])
```

Note: Before actually running the graph of jobs, Iceqube will first verify that the `executable`s specified in all `CommandJob`s are in the `PATH`, making sure we are able to run all `CommandJob`s before actually executing.

When passed to a `PythonFunctionJob`, it returns a python `Context` object, with the following attributes:

```
Context.stdout: command's stdout
Context.stderr: command's stderr
Context.retcode: command's return code
```

When passed to other jobs, it returns the `stdout` as a string.

- `PythonFunctionJob(func: callable, *args, **kwargs)`: Execute a python function with the given args and kwargs. Iceqube looks at the top-level of args and kwargs for job instances, and marks them as dependencies of the job. Note that the function is run as a thread of the current python interpreter, locking up the GIL. Users should use this sparingly.

```python
ffmpeg = CommandJob("ffmpeg", "1080p.mp4")
PythonFunctionJob(is_hd, ffmpeg)
```

`func` is required to return a string, which will be passed to other jobs depending on the `PythonFunctionJob` instance.

- `Job(deps: list_of_jobs)`: A generic, no-op job class that mostly functions as an aggregator of other jobs. If depended on by other jobs, it simply returns an empty string.

# Job class common definitions

`Job(cleanup=None: callable_or_none)`: A python function for when the job has been cancelled or failed. Can be used to clean up any downloaded files.

Note: can be potentially expensive if an almost-finished job graph is cancelled, making us call potentially many cleanup functions, each only able to run once.

`Job.progress: int`: Returns the progress of the current job as an int from 0-100, without taking into account its dependencies' progress.

`Job.aggregate_progress: int`: Returns the job's total progress as an int from 0-100, i.e. its progress and its' dependencies' progress (Iceqube will guarantee that its dependencies are run to completion before the current job is run).

`Job.state`: Returns [one of the current `Job.state`s](https://github.com/learningequality/barbequeue/blob/develop/src/barbequeue/common/classes.py#L36-L42).
`Job.cancel()`: Cancel the current job and all jobs it depends on. Stops any non-running jobs from running, but doesn't affect any currently running jobs.

Note: because jobs are more granularly specified now, the cost of non-preemptive cancelling isn't too big anymore -- worst case, we only have at most N threads running, meaning only N jobs running at any one time. Only those jobs will be uncancelled. It's also much safer, as we don't force interrupt any running job.

# Advantages over current system

1. Stability -- The current Iceqube system has two threads dedicated to simpley reading jobs and passing messages. A refactor of the system would centralize all bookkeeping threads to one single thread, handling job allocation and progress updating.

1. More concurrency -- By separating big python jobs into small subjobs, we allow the Iceqube system to make smart decisions regarding when to run jobs.

1. Speed -- By specifically demarcating any python-specific logic that needs to run, we allow all other jobs, the job dispatcher, and the messaging system, to be implemented in compiled code, improving their speed and allowing more concurrency by circumventing the GIL.

# Use cases

1. Kolibri - Reimplement local and internet content importing as a graph of jobs. This needs robust downloading, file transferring and running python logic on the downloaded files.

1. Ricecooker - Can be refactored to convert the channel tree returned by the sushi chef, into a job graph. Needs file downloading, python logic, running external commands (for `ffmpeg`), and file uploading to the content curation server.

# Open questions

1. Are the specific APIs described here the most convenient ones for the developers of the two projects described above?

1. What other problems are encountered regarding concurrency that Iceqube can address?

**Comment by aronasorman** [comment]
@benjaoming Feedback would be nice here, as the general reviewer of iceqube!

@jamalex @rtibbles feedback would be nice as you both have experience with the content import on Kolibri.

@jayoshih @ivanistheone you both are the maintainers of ricecooker, so feedback would be appreciated here as well.

**Comment by jayoshih** [comment]
For file uploading to CC, we would benefit from using Aziz' json file uploading. However, we will need to fix some bugs with exercises not getting parsed before being written to json. Once that's done, the logic for uploading json to the CC's add nodes method can use the UploadJobs

**Comment by rtibbles** [comment]
One thing I think it would be helpful to think about is dynamic progress - i.e. when the amount of progress that one job will take depends on information only available after the successful completion of another job (the main example that comes to mind here is working out how long content database import will take, which we can only know after we have already downloaded the database file itself).

Thinking about how to have sensible estimates of progress that are also updateable should be an important consideration in order to give a good user experience.

Would the database import be a GIL locking Python function task, or would there be a better way to invoke asynchronous database updates (I would hope so, so that we can, for example, run scheduled database updates to generate automated recommendations during idle times).

**Comment by indirectlylit** [comment]
A couple thoughts/questions from a UI perspective:

* Some jobs have an explicitly indeterminate progress, and there are good UI conventions for showing this. Recommend that all jobs have a boolean `indeterminate_progress` flag or similar.
  * If any child jobs are indeterminate, the parent(s) would be also
  * In @rtibbles' note above about dynamically updated progress, the overall progress would be indeterminate _until_ some initial stages have completed and more info is available
  * In your `DownloadJob` example, neglecting to pass in `bytes` would result in an explicitly indeterminate progress
* Other progress meta-data might be helpful eventually. For example:
  * speed stats
  * some constants representing units of speed
  * time stats, like elapsed, estimated remaining
  * for parent jobs, number of child jobs
* Could also be useful to be able to assign jobs user-facing names so they can be reported back
* How are user-facing errors handled and bubbled up the graph?

**Comment by benjaoming** [comment]
@aronasorman 

Some comments....

 * **Scope and objectives:** While Kolibri probably has a simple job logic (basically a download manager and then sync'ing, which is probably just a single job), it has Python 2 compatibility to wrestle with. Ricecooker doesn't have this, and you can probably make a simpler implementation without worrying too much about the GIL (`concurrent.futures` etc) and the granularity of UI perspectives mentioned by @indirectlylit.
   
   In this case I would propose to keep Iceqube as it is for now, just for Kolibri and aim for cross-platform complexities and future support to be a big challenge and keeping the codebase more simple and clean for the sake of this.
   
   The proposed graph API could be optimized and much easier to maintain and develop by NOT attempting to have it as a Kolibri dependency.
   
   Projects like Ricecooker might also have message brokers like RabbitMQ to communicate from the separate app work (UWSGI or similar). This, combined with django-channels might give us a significantly different set of options.

 * **Making the codebase ready for a refactor:** I found that tests seem to run fine on Travis now, I would suggest that you get the name refactor in place and everything needed for distributing Iceqube before taking further steps.

 * **The graph part of the API:** It's a bit unclear to me how Iceqube will solve dependencies between jobs. Some more API function proposals would be nice (and props for the ones you already gave, makes it easy to understand).
   
   It would also illustrate the graph part with a code example from the Ricecooker implementor's POV.
