### ISSUE TITLE
how to deliver the message

### ISSUE THREAD

**Issue by songyanyi** [learningequality/iceqube#48]
Hello, how to deliver the message?

**Comment by benjaoming** [comment]
Sorry, this project never had documentation written #36 

The question is too hard to answer quickly. You will have to read the tests to get a comprehensible overview of how to invoke.

**Comment by indirectlylit** [comment]
@songyanyi also please note that this library is used internally within Kolibri. It is not being maintained or supported for external usage.

**Comment by benjaoming** [comment]
@indirectlylit this is true - though Iceqube _was_ originally structured to at some point support their wider usage, so currently doesn't have anything that contradicts this -- but it's missing a lot of pieces like documentation and code comments.

Further development will take place as a "vendored" module of Kolibri, so this project will AFAIK be left in the state it's in now.
